language: python
python:
  - "3.6"
  - "3.8"
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - python emuserema/__main__.py --init
  - python emuserema/__main__.py --test
